<?php

namespace App\Actions\Disputes;

use App\Models\Dispute;
use App\Models\EvidenceBundle;
use App\Models\Merchant;
use App\Services\EvidenceService;
use App\Services\ReasonCodeRegistry;

class GenerateDisputeResponse
{
  public function __construct(
    private EvidenceService    $evidenceService,
    private ReasonCodeRegistry $registry,
  ) {}

  /**
   * Generate a structured dispute response document
   * from the locked evidence bundle.
   */
  public function execute(Dispute $dispute, Merchant $merchant): array
  {
    $transaction = $dispute->transaction;
    $bundle      = $transaction->evidenceBundle;

    // Retrieve and verify the evidence bundle
    $evidence = $this->evidenceService->retrieveBundle($bundle, $merchant);

    // Look up the reason code definition
    $reasonCode = $this->registry->find(
      $dispute->network->value,
      $dispute->reason_code
    );

    // Build the structured response document
    $document = [
      'document_version'   => '1.0',
      'generated_at'       => now()->toIso8601String(),
      'dispute'            => [
        'id'             => $dispute->ulid,
        'reason_code'    => $dispute->reason_code,
        'description'    => $dispute->reason_description
          ?? ($reasonCode['description'] ?? 'Unknown'),
        'network'        => strtoupper($dispute->network->value),
        'filed_at'       => $dispute->filed_at?->toIso8601String(),
        'status'         => $dispute->status->value,
      ],
      'merchant'           => [
        'id'             => $merchant->ulid,
        'company_name'   => $merchant->company_name,
      ],
      'transaction'        => [
        'id'             => $transaction->ulid,
        'amount'         => $transaction->amount,
        'currency'       => $transaction->currency,
        'formatted_amount' => $transaction->currency . ' ' .
          number_format($transaction->amount / 100, 2),
        'processed_at'   => $transaction->created_at->toIso8601String(),
        'decision'       => $transaction->decision->value,
        'risk_score'     => $transaction->risk_score,
        'risk_level'     => $transaction->risk_level->value,
      ],
      'evidence'           => [
        'bundle_id'      => $bundle->ulid,
        'signature_valid' => $evidence['signature_valid'],
        'hmac_signature' => $bundle->hmac_signature,
        'locked_at'      => $bundle->created_at->toIso8601String(),
        'payload'        => $evidence['payload'],
      ],
      'response_strategy'  => $reasonCode['response_strategy']
        ?? 'Submit evidence bundle demonstrating transaction legitimacy.',
      'winning_argument'   => $reasonCode['winning_argument']
        ?? 'Evidence bundle provides cryptographic proof of legitimate transaction.',
      'required_evidence'  => $reasonCode['required_evidence'] ?? [],
      'time_limit_days'    => $reasonCode['time_limit_days'] ?? 120,
      'risk_signals'       => $this->formatSignals($evidence['payload']),
      'summary'            => $this->buildSummary($dispute, $transaction, $evidence),
    ];

    return $document;
  }

  private function formatSignals(array $payload): array
  {
    return collect($payload['risk']['signals'] ?? [])
      ->map(fn($s) => [
        'signal'        => $s['signal_name'],
        'value'         => $s['raw_value'],
        'score'         => $s['normalized_score'],
        'weight'        => $s['weight'],
        'contribution'  => $s['weighted_contribution'],
      ])
      ->toArray();
  }

  private function buildSummary(
    Dispute $dispute,
    $transaction,
    array $evidence
  ): string {
    $amount    = $transaction->currency . ' ' .
      number_format($transaction->amount / 100, 2);
    $score     = $transaction->risk_score;
    $decision  = ucfirst($transaction->decision->value);
    $lockedAt  = $evidence['payload']['locked_at'] ?? 'unknown';
    $sigValid  = $evidence['signature_valid'] ? 'VALID' : 'INVALID';

    return "This dispute response was automatically generated by Chargeback Shield " .
      "(Atlas Tech) in response to a {$dispute->network->value} chargeback " .
      "(Reason Code {$dispute->reason_code}) filed against transaction " .
      "{$transaction->ulid}. " .
      "The transaction for {$amount} was processed with a composite risk score " .
      "of {$score} (Decision: {$decision}). " .
      "A cryptographically signed evidence bundle was locked at {$lockedAt} " .
      "with HMAC-SHA256 signature status: {$sigValid}. " .
      "This bundle serves as tamper-proof evidence that the transaction was " .
      "legitimate at the time of authorization.";
  }
}
